name: ELisp CI

on:
  workflow_dispatch:
  schedule:
    - cron: '10 20 * * *'
  pull_request:
    paths:
      - '**.zig'
      - '**.yml'
  push:
    paths:
      - '**.zig'
      - '**.yml'

jobs:
  lisp-test:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        emacs_version:
          - 28.2
          - 29.4
          - 30.1
          - snapshot
    steps:
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0
      - uses: actions/checkout@v4
      - name: Run test
        run: |
          make test
