name: ELisp CI

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '**.zig'
      - '**.yml'
  push:
    paths:
      - '**.zig'
      - '**.yml'

jobs:
  lisp-test:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: mlugg/setup-zig@v2
      - uses: actions/checkout@v4
      - name: Install emacs
        run: |
          sudo apt update && sudo apt install -y emacs
      - name: Run test
        run: |
          emacs --version
          make test
